<?php
echo"Geeky shows";echo"<br>";
echo 'I am a good boy';echo"<br>";
echo 25.045;echo"<br>";
echo("geeky show");echo"<br>"; 
echo"Visit","geekyShows";echo"<br>";
echo"Visit"."geekyshows";echo"<br>";
echo"<b>GeekyShows</b>";echo"<br>";
echo"<b>"."GeekyShows"."</b>";echo"<br>";
echo"<b>","GeekyShows","</b>";echo"<br>";
echo"<u><h1>visit Geeky Shows</h1></u>";echo"<br>"; 
$value1=10;
$value2=20;
$sum=$value1+$value2;
echo $sum;echo"<br>";
echo $value1;echo"<br>";
echo "value is:",$value1;echo"<br>";
echo "value is:".$value1;echo"<br>";
echo $value1+$value2;echo"<br>";
echo "Total   ".($value1+$value2);echo"<br>";
echo "<b>Total</b>",$sum;echo"<br>";
echo "<b>Total</b>".$sum;echo"<br>";
$name="geekyShows";
echo $name;echo"<br>";
echo "welcome to ".$name;echo"<br>";
echo "dell";echo"<br>";
echo "<b>".$name."</b>";echo"<br>";
echo $name." <b> and </b> ".$name;echo"<br>";echo"<br>";
$num=" RAM LOVES SITA ";
print $num;
?>